services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pizza_bot
    env_file:
      - .env 
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - db
    networks:
      - pizza_network
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    restart: always
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_network
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always

networks:
  pizza_network:
    driver: bridge

volumes:
  postgres_data:
